"""Add image column to Books model

Revision ID: 38342eb61dda
Revises: f0231bb4f2c3
Create Date: 2023-07-17 18:22:36.937232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38342eb61dda'
down_revision = 'f0231bb4f2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
