# Generated by Django 4.1 on 2023-07-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blog_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
