# Generated by Django 4.1 on 2023-07-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
