# Generated by Django 4.1 on 2023-07-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=256)),
                ('task_status', models.CharField(max_length=256)),
                ('task_description', models.TextField()),
            ],
        ),
    ]
