# Generated by Django 4.1 on 2023-07-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_todolist_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='task_description',
            field=models.CharField(max_length=256),
        ),
    ]
